### ISSUE TITLE
I'm building a video streaming site for Opera

### ISSUE THREAD

**Issue by ISNIT0** [BMSVieira/moovie.js#4]
I'm building a video streaming site for Operas (2-3 hours long).
I had never considered that the `<video>` element was not suitable for this.
Moovie.js calls itself a "Movie focused HTML5 Player". What does that mean, and what's wrong with the HTML5 `<video>` element?

**Comment by BMSVieira** [comment]
Hey there,
Well, there is nothing wrong with the "video" element, in fact, moovie.js is built on top of the HTML5 native video element as you may see in read me file. 
It call itself "made for movies" because it has specific features that most people need when they are watching a movie or a long subtitled video, for example: adjust offset on the fly, support for .srt and .vtt captions.
other than that, works perfectly fine as other native <video> element would perform.
